nameOverride: ""
fullnameOverride: ""

global:
  openai:
    apiKey: sk-XXXX

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

api:
  replicaCount: 1
  image:
    repository: aatt-ps-rag-api
    tag: latest
    pullPolicy: IfNotPresent
  env:
    CHROMA_HOST: chroma-service
    CHROMA_PORT: "8000"
    COLLECTION_NAME: aatt_practice_statements
    MODEL_NAME: gpt-4o-mini
    EMBEDDING_MODEL: huggingface:all-MiniLM-L6-v2
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

chroma:
  replicaCount: 1
  image:
    repository: chromadb/chroma
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: chroma-service
    type: ClusterIP
    port: 8000
  env:
    CHROMA_SERVER_HOST: 0.0.0.0
    CHROMA_SERVER_PORT: "8000"
    IS_PERSISTENT: "TRUE"
    PERSIST_DIRECTORY: /data
  persistence:
    enabled: true
    existingClaim: ""
    storageClass: hostpath
    size: 2Gi

builderJob:
  enabled: true
  backoffLimit: 1
  image:
    repository: aatt-ps-rag-build-vector-db
    tag: latest
    pullPolicy: IfNotPresent
  env:
    CHROMA_HOST: chroma-service
    CHROMA_PORT: "8000"
    COLLECTION_NAME: aatt_practice_statements
