apiVersion: v1
kind: Service
metadata:
  name: {{ include "ps-rag.api.serviceName" . }}
  labels:
    {{- include "ps-rag.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ps-rag.api.name" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: 8080
      {{- if and .Values.api.service.nodePort (eq .Values.api.service.type "NodePort") }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
