apiVersion: v1
kind: Service
metadata:
  name: {{ include "ps-rag.chroma.serviceName" . }}
  labels:
    {{- include "ps-rag.labels" . | nindent 4 }}
    app.kubernetes.io/component: chroma
spec:
  type: {{ .Values.chroma.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ps-rag.chroma.name" . }}
    app.kubernetes.io/component: chroma
  ports:
    - port: {{ .Values.chroma.service.port }}
      targetPort: {{ .Values.chroma.service.port }}
      protocol: TCP
      name: http
